### ISSUE TITLE
Ingressroute Load Balancing and Healthcheck settings has no affect to upstream service choices

### ISSUE THREAD

**Issue by yutaokaz** [heptio/gimbal#186] opened 2018-07-23 04:50 UTC
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**:

BUG REPORT.

**What happened**:

I tried to set load balancing method as strategy at ingressroute.yaml file, but each method looks no affects to Upstream RPS nor Upstream CPS in Grafana dashboard. And (includes defaults) RoundRobin method sometimes choice same upstream service from 1 gimbal pod.
I succeeded to set Healthcheck path, but even if upstream service returns 503 response for envoy healthchecking, envoy continues choice this service.

**What you expected to happen**:

I considering heptio/contour couldn't set envoy correctly (envoyproxy's bug?), or I just misunderstood.

**How to reproduce it (as minimally and precisely as possible)**:

Bellow is my ingressroute.yaml.

```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: yj-yutaokaz-ingressroute
  namespace: yj-yutaokaz
spec:
  virtualhost:
    fqdn: yj-yutaokaz.local
  routes:
    - match: /
      services:
        - name: k8s01-yutaokaz-service80
          port: 80
          strategy: RoundRobin
        - name: os01-yutaokaz-service80
          port: 80
          strategy: RoundRobin
          healthCheck:
            path: /503.php
```

**Anything else we need to know?**:

I reading below documentation to configure ingressroute.
https://github.com/heptio/contour/blob/v0.6.0-beta.1/design/ingressroute-design.md

**Environment**:

- Gimbal version (Gimbal git repository tag):
https://github.com/heptio/gimbal/tree/release-0.3.0-beta.1
- Contour version:
gcr.io/heptio-images/contour:v0.6.0-beta.1
- kubernetes-discoverer version:
- openstack-discoverer version (if applicable):
gcr.io/heptio-images/gimbal-discoverer:v0.3.0-beta.1

**Comment by stevesloka** [comment] 2018-07-24 01:48
Hey @yutaokaz! I want to break this issue up to help make it more clear. 

> I tried to set load balancing method as strategy at ingressroute.yaml file, but each method looks no affects to Upstream RPS nor Upstream CPS in Grafana dashboard. And (includes defaults) RoundRobin method sometimes choice same upstream service from 1 gimbal pod.

The default (if not specified) is `RoundRobin` for any upstream. Envoy implements this and I've also seen that requests do not always switch hosts for each request. Is this the issue you are describing?

> I succeeded to set Healthcheck path, but even if upstream service returns 503 response for envoy healthchecking, envoy continues choice this service.

Could you try the following steps?

1.  Port-forward to port `9001` to an envoy pod and bring up the admin web ui. 
2. Look at `/stats` and search for your service
3. Following is an example, I have 3 pods running and one of the pods is failing the healthcheck, so Envoy reports only `2` healthy: 

```
cluster.default/kuard/80.health_check.healthy: 2
```

Here are the docs on the HealthCheck stats emitted by Envoy: https://www.envoyproxy.io/docs/envoy/latest/configuration/cluster_manager/cluster_stats#health-check-statistics

**Comment by stevesloka** [comment] 2018-07-24 03:15
Also there is a panic threshold that might have an effect: https://www.envoyproxy.io/docs/envoy/v1.6.0/intro/arch_overview/load_balancing#panic-threshold

**Comment by yutaokaz** [comment] 2018-07-24 03:48
Hi @stevesloka , thank you for your reply.

> Envoy implements this and I've also seen that requests do not always switch hosts for each request. Is this the issue you are describing?

Yes, I understand that is normal RoundRobin behavior. How about all method looks have no affect to Upstream RPS nor Upstream CPS? I want to know how to check each load balance method works fine I defined.

Below is my healthcheck status, and Envoy still selects this unhealthy service.

```bash
$ curl -s localhost:9001/stats | grep 'health_check'
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.attempt: 38
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.failure: 38
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.healthy: 0
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.network_failure: 0
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.passive_failure: 0
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.success: 0
cluster.yj-yutaokaz/os02-yutaokaz-a5e37d/80.health_check.verify_cluster: 0
http.admin.tracing.tracing.health_check: 0
http.ingress_http.tracing.health_check: 0
http.stats.tracing.health_check: 0
```

**Comment by yutaokaz** [comment] 2018-07-24 04:07
Thank you for useful documentation.

> The default panic threshold is 50%.

Actually I set 4 services to route. Didn't healthcheck setting avoid unhealthy service?

**Comment by stevesloka** [comment] 2018-07-24 13:38
@yutaokaz are you wanting to verify the different Load Balancing Algorithms work as intended? Let me see if I can find how others have done that inside Envoy. 

If all 4 services failed the health check by default Envoy will still send traffic. I opened an issue in Contour to allow that setting to be configurable: https://github.com/heptio/contour/issues/579

**Comment by yutaokaz** [comment] 2018-07-25 08:07
@stevesloka Yes, I want it.

I'm sorry, I had misunderstood about healthcheck. It's not for per route, but for per service. So I create 3 endpoints for 1 service, then I succeed to stop requesting to unhealthy (healthcheck failed) endpoint, and now I understand about 50% panic threshold.
Thank you for create an issue! I really want setting this, and I expecting Envoy will be not select unhealthy (all endpoints downed, cluster broken, or something happened) service.

**Comment by rosskukulinski** [comment] 2018-07-27 04:46
@yutaokaz this feature was merged into Contour in https://github.com/heptio/contour/issues/579 as part of Contour `v0.6.0-beta.2`.  Gimbal v0.3.0-beta.2 includes this latest release of Contour.

**Closed by rosskukulinski** 2018-07-27 04:46 UTC
